apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004 # port in the worker node from where the application will be accesible
  selector:
    app: myapp # matches the label in the pod definition in the deployment