apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: myapp-replicaset
 labels:
   app: myapp
spec:
  selector:
    matchLabels:
     app: myapp # Same as label in the template section for the pod
  replicas: 3
  template: # template of the pods
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
      