apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080
        #For Http
      readinessProbe:
        httpGet:
          path: /api/ready
          port: 8080
        initialDelaySeconds: 10 # wait in seconds for the probe
        periodSeconds: 5 # retry the probe every 5 sec
        failureThreshold: 5 # times the probe should be executed, by default is 3
      # For socket
      # readinessProbe:
        # tcpSocket:
          # port: 3306
      # For command:
      # readinessProbe:
      #   exec:
      #     command:
      #       - cat
      #       - /app/is_ready
      livenessProbe:  # Socket and Command have the same options
        httpGet:
          path: /api/ready
          port: 8080
        initialDelaySeconds: 10 # wait in seconds for the probe
        periodSeconds: 5 # retry the probe every 5 sec
        failureThreshold: 5 # times the probe should be executed, by default is 3
