apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deployment
 labels:
   app: nginx
   tier: frontend
spec:
  selector:
    matchLabels:
     app: myapp # Same as label in the template section for the pod
  replicas: 4
  template: # template of the pods
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:1.18
      